site_name: My Docs

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

# Extensions
markdown_extensions:
  - admonition
